"""create initial policy assignment schema

Revision ID: 4b4588f8f805
Revises: 
Create Date: 2026-09-16 22:01:29.905546
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4b4588f8f805'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('token_prefix', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_api_credentials_lifecycle', 'api_credentials', ['revoked_at', 'expires_at'], unique=False)
    op.create_index('ix_api_credentials_subject', 'api_credentials', ['subject'], unique=False)
    op.create_table('assignment_field_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cardinality', sa.String(length=10), nullable=False),
    sa.Column('conflict_resolution', sa.String(length=50), nullable=False),
    sa.Column('input', sa.JSON(), server_default='{"type":"text","options":[]}', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_actor', 'audit_logs', ['actor'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_table('condition_field_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('allowed_operators', sa.JSON(), nullable=False),
    sa.Column('input', sa.JSON(), nullable=False),
    sa.Column('resolver_key', sa.String(length=200), nullable=True),
    sa.Column('source_table', sa.String(length=100), nullable=True),
    sa.Column('source_column', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint("(field_type = 'static' AND source_table IS NOT NULL AND source_column IS NOT NULL) OR (field_type = 'derived' AND resolver_key IS NOT NULL)", name='ck_condition_field_definition_source'),
    sa.CheckConstraint("field_type IN ('static', 'derived')", name='ck_condition_field_definition_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index('ix_condition_field_definitions_catalog_filters', 'condition_field_definitions', ['active', 'field_type', 'data_type'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('employee_type', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("state_code IN ('AK', 'AL', 'AR', 'AS', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'GU', 'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MP', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'PR', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VI', 'VT', 'WA', 'WI', 'WV', 'WY')", name='ck_employees_state_code'),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_manager_id'), 'employees', ['manager_id'], unique=False)
    op.create_index('ix_employees_population_filters', 'employees', ['state_code', 'department', 'employee_type'], unique=False)
    op.create_index('ix_employees_start_date', 'employees', ['start_date'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_throttles',
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('failed_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('window_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key_hash')
    )
    op.create_table('oauth_clients',
    sa.Column('client_id', sa.String(length=200), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=False),
    sa.Column('redirect_uris', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_policies_status_created', 'policies', ['status', 'created_at'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('employee_scope', sa.String(length=30), server_default='none', nullable=False),
    sa.Column('assignment_field_scope', sa.String(length=20), server_default='none', nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("assignment_field_scope IN ('all', 'selected', 'none')", name='ck_role_assignment_field_scope'),
    sa.CheckConstraint("employee_scope IN ('all', 'reporting_tree', 'self', 'none')", name='ck_role_employee_scope'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scheduled_reconciliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=100), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status = 'processed' AND processed_at IS NOT NULL) OR (status IN ('pending', 'cancelled') AND processed_at IS NULL)", name='ck_scheduled_reconciliation_processed_at'),
    sa.CheckConstraint("status IN ('pending', 'processed', 'cancelled')", name='ck_scheduled_reconciliation_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'trigger_type', 'scheduled_at', name='uq_scheduled_reconciliation_event')
    )
    op.create_index('ix_scheduled_reconciliations_due', 'scheduled_reconciliations', ['status', 'scheduled_at'], unique=False)
    op.create_index('ix_scheduled_reconciliations_entity', 'scheduled_reconciliations', ['entity_type', 'entity_id'], unique=False)
    op.create_table('condition_field_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condition_field_definition_id', sa.Integer(), nullable=False),
    sa.Column('dependency_type', sa.String(length=20), nullable=False),
    sa.Column('dependency_key', sa.String(length=200), nullable=False),
    sa.Column('source_table', sa.String(length=100), nullable=True),
    sa.Column('source_column', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=100), server_default='value', nullable=False),
    sa.Column('impact_resolver_key', sa.String(length=200), nullable=False),
    sa.CheckConstraint("dependency_type IN ('column', 'relationship', 'time')", name='ck_condition_field_dependency_type'),
    sa.ForeignKeyConstraint(['condition_field_definition_id'], ['condition_field_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('condition_field_definition_id', 'dependency_key', 'role', name='uq_condition_field_dependency')
    )
    op.create_index(op.f('ix_condition_field_dependencies_condition_field_definition_id'), 'condition_field_dependencies', ['condition_field_definition_id'], unique=False)
    op.create_table('conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condition_field_definition_id', sa.Integer(), nullable=False),
    sa.Column('operator', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['condition_field_definition_id'], ['condition_field_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_group_memberships',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('employee_id', 'group_id')
    )
    op.create_table('employee_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('assignment_field_definition_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignment_field_definition_id'], ['assignment_field_definitions.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_employee_overrides_employee_retired', 'employee_overrides', ['employee_id', 'retired_at'], unique=False)
    op.create_table('employee_policies',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('employee_id', 'policy_id')
    )
    op.create_table('group_policies',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'policy_id')
    )
    op.create_table('policy_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.CheckConstraint('effective_until IS NULL OR effective_until >= effective_from', name='ck_policy_version_valid_effective_range'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id', 'version_number')
    )
    op.create_index(op.f('ix_policy_versions_policy_id'), 'policy_versions', ['policy_id'], unique=False)
    op.create_table('role_assignment_field_scopes',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assignment_field_definition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_field_definition_id'], ['assignment_field_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'assignment_field_definition_id')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('is_root', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('password_change_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('mfa_secret_ciphertext', sa.String(length=1000), nullable=True),
    sa.Column('mfa_recovery_code_hashes', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active', 'suspended', 'disabled')", name='ck_user_status'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_index('ix_users_status', 'users', ['status'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reauthenticated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('mfa_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_ip', sa.String(length=64), nullable=True),
    sa.Column('last_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('pending_mfa_secret_ciphertext', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_auth_sessions_expiry', 'auth_sessions', ['expires_at'], unique=False)
    op.create_index('ix_auth_sessions_user_lifecycle', 'auth_sessions', ['user_id', 'revoked_at', 'expires_at'], unique=False)
    op.create_table('compiled_policy_clauses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compiled_policy_clauses_policy_version_id'), 'compiled_policy_clauses', ['policy_version_id'], unique=False)
    op.create_table('condition_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_version_id', sa.Integer(), nullable=False),
    sa.Column('parent_group_id', sa.Integer(), nullable=True),
    sa.Column('logical_operator', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['parent_group_id'], ['condition_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('assignment_field_definition_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('source_policy_version_id', sa.Integer(), nullable=True),
    sa.Column('source_override_id', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(source_policy_version_id IS NOT NULL AND source_override_id IS NULL) OR (source_policy_version_id IS NULL AND source_override_id IS NOT NULL)', name='ck_employee_assignment_exactly_one_source'),
    sa.CheckConstraint('effective_until IS NULL OR effective_until > effective_from', name='ck_employee_assignment_valid_effective_range'),
    sa.ForeignKeyConstraint(['assignment_field_definition_id'], ['assignment_field_definitions.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_override_id'], ['employee_overrides.id'], name='fk_employee_assignments_source_override_id'),
    sa.ForeignKeyConstraint(['source_policy_version_id'], ['policy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_employee_assignments_employee_assignment_field_start', 'employee_assignments', ['employee_id', 'assignment_field_definition_id', 'effective_from'], unique=False)
    op.create_index('ix_employee_assignments_employee_current', 'employee_assignments', ['employee_id', 'effective_until'], unique=False)
    op.create_table('oauth_authorization_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('redirect_uri', sa.String(length=1000), nullable=False),
    sa.Column('code_challenge', sa.String(length=200), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('resource', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reauthenticated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mfa_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_hash')
    )
    op.create_index('ix_oauth_authorization_codes_expiry', 'oauth_authorization_codes', ['expires_at', 'used_at'], unique=False)
    op.create_table('oauth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token_hash', sa.String(length=64), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_prefix', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('resource', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('access_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refresh_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reauthenticated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mfa_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token_hash'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_index('ix_oauth_tokens_access_lifecycle', 'oauth_tokens', ['access_expires_at', 'revoked_at'], unique=False)
    op.create_index('ix_oauth_tokens_refresh_lifecycle', 'oauth_tokens', ['refresh_expires_at', 'revoked_at'], unique=False)
    op.create_index('ix_oauth_tokens_user', 'oauth_tokens', ['user_id', 'revoked_at'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_password_reset_tokens_expiry', 'password_reset_tokens', ['expires_at', 'used_at'], unique=False)
    op.create_index('ix_password_reset_tokens_user', 'password_reset_tokens', ['user_id', 'created_at'], unique=False)
    op.create_table('policy_field_values',
    sa.Column('policy_version_id', sa.Integer(), nullable=False),
    sa.Column('assignment_field_definition_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['assignment_field_definition_id'], ['assignment_field_definitions.id'], ),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('policy_version_id', 'assignment_field_definition_id', 'value')
    )
    op.create_table('security_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('details', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("severity IN ('info', 'warning', 'critical')", name='ck_security_event_severity'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_security_events_severity', 'security_events', ['severity', 'created_at'], unique=False)
    op.create_index('ix_security_events_user_created', 'security_events', ['user_id', 'created_at'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_table('compiled_policy_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clause_id', sa.Integer(), nullable=False),
    sa.Column('condition_field_definition_id', sa.Integer(), nullable=False),
    sa.Column('operator', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['compiled_policy_clauses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['condition_field_definition_id'], ['condition_field_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compiled_policy_conditions_clause_id'), 'compiled_policy_conditions', ['clause_id'], unique=False)
    op.create_table('condition_group_conditions',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['conditions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['condition_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'condition_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('condition_group_conditions')
    op.drop_index(op.f('ix_compiled_policy_conditions_clause_id'), table_name='compiled_policy_conditions')
    op.drop_table('compiled_policy_conditions')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('ix_security_events_user_created', table_name='security_events')
    op.drop_index('ix_security_events_severity', table_name='security_events')
    op.drop_table('security_events')
    op.drop_table('policy_field_values')
    op.drop_index('ix_password_reset_tokens_user', table_name='password_reset_tokens')
    op.drop_index('ix_password_reset_tokens_expiry', table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index('ix_oauth_tokens_user', table_name='oauth_tokens')
    op.drop_index('ix_oauth_tokens_refresh_lifecycle', table_name='oauth_tokens')
    op.drop_index('ix_oauth_tokens_access_lifecycle', table_name='oauth_tokens')
    op.drop_table('oauth_tokens')
    op.drop_index('ix_oauth_authorization_codes_expiry', table_name='oauth_authorization_codes')
    op.drop_table('oauth_authorization_codes')
    op.drop_index('ix_employee_assignments_employee_current', table_name='employee_assignments')
    op.drop_index('ix_employee_assignments_employee_assignment_field_start', table_name='employee_assignments')
    op.drop_table('employee_assignments')
    op.drop_table('condition_groups')
    op.drop_index(op.f('ix_compiled_policy_clauses_policy_version_id'), table_name='compiled_policy_clauses')
    op.drop_table('compiled_policy_clauses')
    op.drop_index('ix_auth_sessions_user_lifecycle', table_name='auth_sessions')
    op.drop_index('ix_auth_sessions_expiry', table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index('ix_users_status', table_name='users')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_table('role_assignment_field_scopes')
    op.drop_index(op.f('ix_policy_versions_policy_id'), table_name='policy_versions')
    op.drop_table('policy_versions')
    op.drop_table('group_policies')
    op.drop_table('employee_policies')
    op.drop_index('ix_employee_overrides_employee_retired', table_name='employee_overrides')
    op.drop_table('employee_overrides')
    op.drop_table('employee_group_memberships')
    op.drop_table('conditions')
    op.drop_index(op.f('ix_condition_field_dependencies_condition_field_definition_id'), table_name='condition_field_dependencies')
    op.drop_table('condition_field_dependencies')
    op.drop_index('ix_scheduled_reconciliations_entity', table_name='scheduled_reconciliations')
    op.drop_index('ix_scheduled_reconciliations_due', table_name='scheduled_reconciliations')
    op.drop_table('scheduled_reconciliations')
    op.drop_table('roles')
    op.drop_index('ix_policies_status_created', table_name='policies')
    op.drop_table('policies')
    op.drop_table('oauth_clients')
    op.drop_table('login_throttles')
    op.drop_table('groups')
    op.drop_index('ix_employees_start_date', table_name='employees')
    op.drop_index('ix_employees_population_filters', table_name='employees')
    op.drop_index(op.f('ix_employees_manager_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index('ix_condition_field_definitions_catalog_filters', table_name='condition_field_definitions')
    op.drop_table('condition_field_definitions')
    op.drop_index('ix_audit_logs_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('assignment_field_definitions')
    op.drop_index('ix_api_credentials_subject', table_name='api_credentials')
    op.drop_index('ix_api_credentials_lifecycle', table_name='api_credentials')
    op.drop_table('api_credentials')
    # ### end Alembic commands ###
